setwd('C:\\Users\\Ivan.Liuyanfeng\\Desktop\\ata_Mining_Work_Space\\rdatamining')
dim(iris)
names(iris)
str(iris)
attributes(iris)
iris[1:5,]
iris[1:10,1]
iris[,1][1:10]
summary(iris)
table(iris[,5])
pie(table(iris[,5]))
var(iris[,1])
cov(iris[,1],iris[,3])
cor(iris[,1],iris[,3])
hist(iris[,1])
plot(density(iris[,1]))
plot(iris[,1],iris[,2])
plot(iris)
pairs(iris)
